apiVersion: v1
kind: Service
metadata:
  name: backend-service-nodeport
  namespace: jokes-api
  labels:
    app: jokes-api
    component: backend
spec:
  type: NodePort
  selector:
    app: jokes-api
    component: backend
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30500 # Access via <node-ip>:30500
      protocol: TCP
  sessionAffinity: None
