apiVersion: v1
kind: ConfigMap
metadata:
  name: jokes-api-config
  namespace: jokes-api
  labels:
    app: jokes-api
data:
  # Backend configuration
  NODE_ENV: "production"
  PORT: "5000"

  # Frontend configuration
  API_URL: "http://backend-service:5000"
