apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: jokes-api
  labels:
    app: jokes-api
    component: database
type: Opaque
data:
  POSTGRES_USER: pgUser
  POSTGRES_PASSWORD: pgPass
  POSTGRES_DB: db
